Repository lotteon2/dailyon-sns-service, pull requests merged in 2024-01, with the labels that each got.

#43 [FIX] fix 남 프로필 정보 조회 수정
  src/main/java/com/dailyon/snsservice/controller/rest/PostApiController.java
  src/main/java/com/dailyon/snsservice/repository/post/PostRepository.java
  src/main/java/com/dailyon/snsservice/repository/post/PostRepositoryImpl.java
  src/main/java/com/dailyon/snsservice/service/post/PostService.java
Labels: release

#44 Feat/sns management
  src/main/java/com/dailyon/snsservice/controller/rest/PostAdminController.java
  src/main/java/com/dailyon/snsservice/dto/response/post/PostAdminPageResponse.java
  src/main/java/com/dailyon/snsservice/dto/response/post/PostAdminResponse.java
  src/main/java/com/dailyon/snsservice/exception/common/DomainException.java
  src/main/java/com/dailyon/snsservice/exception/common/EntityNotFoundException.java
  src/main/java/com/dailyon/snsservice/exceptionhandler/advice/ApiControllerAdvice.java
  src/main/java/com/dailyon/snsservice/repository/post/PostJpaRepository.java
  src/main/java/com/dailyon/snsservice/repository/post/PostRepository.java
  src/main/java/com/dailyon/snsservice/repository/post/PostRepositoryImpl.java
  src/main/java/com/dailyon/snsservice/service/post/PostAdminService.java
  src/main/java/com/dailyon/snsservice/service/post/PostService.java
Labels: documentation, enhancement

#45 release
  src/main/java/com/dailyon/snsservice/controller/rest/PostAdminController.java
  src/main/java/com/dailyon/snsservice/dto/response/post/PostAdminPageResponse.java
  src/main/java/com/dailyon/snsservice/dto/response/post/PostAdminResponse.java
  src/main/java/com/dailyon/snsservice/exception/common/DomainException.java
  src/main/java/com/dailyon/snsservice/exception/common/EntityNotFoundException.java
  src/main/java/com/dailyon/snsservice/exceptionhandler/advice/ApiControllerAdvice.java
  src/main/java/com/dailyon/snsservice/repository/post/PostJpaRepository.java
  src/main/java/com/dailyon/snsservice/repository/post/PostRepository.java
  src/main/java/com/dailyon/snsservice/repository/post/PostRepositoryImpl.java
  src/main/java/com/dailyon/snsservice/service/post/PostAdminService.java
  src/main/java/com/dailyon/snsservice/service/post/PostService.java
Labels: documentation, release

#46 [FEAT] add sns search for admin page
  src/main/java/com/dailyon/snsservice/controller/rest/PostAdminController.java
  src/main/java/com/dailyon/snsservice/repository/post/PostJpaRepository.java
  src/main/java/com/dailyon/snsservice/repository/post/PostRepository.java
  src/main/java/com/dailyon/snsservice/repository/post/PostRepositoryImpl.java
  src/main/java/com/dailyon/snsservice/service/post/PostAdminService.java
Labels: documentation, enhancement

#48 [FIX] fix postlike count
  src/main/java/com/dailyon/snsservice/service/post/PostService.java
  src/main/java/com/dailyon/snsservice/service/postlike/PostLikeService.java
  src/main/java/com/dailyon/snsservice/vo/PostCountVO.java
Labels: bug

#50 Fix/fix fetchjoin with pagination
  src/main/java/com/dailyon/snsservice/repository/post/PostJpaRepository.java
  src/main/java/com/dailyon/snsservice/repository/post/PostRepositoryImpl.java
Labels: bug, documentation, enhancement

#51 Develop
  src/main/java/com/dailyon/snsservice/repository/post/PostJpaRepository.java
  src/main/java/com/dailyon/snsservice/repository/post/PostRepositoryImpl.java
Labels: release

#52 Fix/fetchjoin with pagination
  src/main/java/com/dailyon/snsservice/repository/comment/CommentJpaRepository.java
  src/main/java/com/dailyon/snsservice/repository/comment/CommentRepositoryImpl.java
  src/main/java/com/dailyon/snsservice/repository/follow/FollowJpaRepository.java
  src/main/java/com/dailyon/snsservice/repository/follow/FollowRepositoryImpl.java
  src/main/java/com/dailyon/snsservice/service/post/PostAdminService.java
Labels: bug, documentation, enhancement

#54 [FIX] fix select query
  src/main/java/com/dailyon/snsservice/repository/comment/CommentRepositoryImpl.java
  src/main/java/com/dailyon/snsservice/repository/follow/FollowRepositoryImpl.java
Labels: bug

#55 release
  src/main/java/com/dailyon/snsservice/repository/comment/CommentRepositoryImpl.java
  src/main/java/com/dailyon/snsservice/repository/follow/FollowRepositoryImpl.java
Labels: bug

#56 [FIX] fix ootd search query
  src/main/java/com/dailyon/snsservice/repository/post/PostRepositoryImpl.java
Labels: release

#59 [FIX] add redis compression
  build.gradle
  src/main/java/com/dailyon/snsservice/cache/PostCountRedisRepository.java
  src/main/java/com/dailyon/snsservice/cache/Top4OOTDRedisRepository.java
  src/main/java/com/dailyon/snsservice/config/CacheConfig.java
  src/main/java/com/dailyon/snsservice/config/RedisConfig.java
  src/main/java/com/dailyon/snsservice/scheduler/PostScheduler.java
  src/test/java/com/dailyon/snsservice/repository/post/PostCountRedisRepositoryTest.java
  src/test/java/com/dailyon/snsservice/service/CommentServiceTest.java
  src/test/java/com/dailyon/snsservice/service/PostLikeServiceTest.java
  src/test/java/com/dailyon/snsservice/service/PostServiceTest.java
Labels: documentation, enhancement
